### ISSUE TITLE
DLI Link broken

### ISSUE THREAD

**Issue by qalqi** [ChillarAnand/ProjectChalam#7]
When accessed first book Zilla Munusif Court Tirupulu http://www.projectchalam.com/ebooks/16525/ 
the corresponding Resources link 
http://www.new.dli.ernet.in/handle/2015/392775
is down. This may be due to Digital Library of India is undergoing updates.

I suggest to add mirror for every URL from archive.org
Here is existing link mapped to archive.org with a noticeable regex pattern
http://www.new.dli.ernet.in/handle/2015/392775
https://archive.org/details/in.ernet.dli.2015.392775

**Comment by ChillarAnand** [comment]
@qalqi Thanks for reporting the issue and suggesting a solution.

We will soon add mirror URLs also.

**Comment by ChillarAnand** [comment]
@udaybhaskar-v @santhoshchgit  DLI servers are not that reliable. They can go down anytime. Find a good mirror that keeps up to date or we have to create a new mirror.

**Comment by ChillarAnand** [comment]
Closing this as we are not linking broken links in v2.
